"""Public webhook receiver — token in URL is the authentication.

External services (Zapier, Make, Slack actions, custom integrations) POST
to ``/api/webhooks/automation/{token}`` to fire a run of the bound
automation. The token is generated by
:func:`backend.db_automation.create_webhook` and is the ONLY credential —
revocation means disabling or deleting the row.

Authentication boundary:

* No ``Depends(get_current_user)`` — the request carries no session.
* The token lookup runs inside :func:`system_context` (RLS bypass) because
  there's no tenant binding on an anonymous request. The lookup is read-
  only by definition; the only mutation we perform under bypass is the
  ``mark_webhook_triggered`` counter bump, which is bounded to a single
  row identified by the token holder.

Rate limiting is aggressive (60/minute per IP) because the surface is
publicly addressable. A misbehaving integration burning through quota
will surface as a 429 in their dashboard, not as an infinite stream of
queued runs in ours.

Phase 1 (this commit) just acknowledges the trigger and returns the new
``run_id``. A later wave will plumb the POST body through to the run's
input params so flows can branch on payload contents.
"""
from __future__ import annotations

import asyncio
import logging

from fastapi import APIRouter, HTTPException, Request

from .. import db_automation
from ..middleware_rls import system_context
from ..rate_limit import limiter

logger = logging.getLogger("cloakbrowser.webhooks")
router = APIRouter(prefix="/api/webhooks", tags=["webhooks"])


@router.post("/automation/{token}")
@limiter.limit("60/minute")
async def trigger_automation(token: str, request: Request):  # noqa: ARG001
    """Fire-and-forget run trigger for the webhook identified by ``token``.

    Returns 404 for an unknown / disabled token (do not distinguish — we
    don't want to confirm token existence to a probing caller). On
    success returns 200 with ``{"received": true, "run_id": ..., "status": "queued"}``
    so the integration can correlate / surface a deep link to the run.

    ``request`` is declared so slowapi's rate-limit decorator can read it
    (the per-IP key extractor needs the Starlette request object).
    """
    # The token lookup itself is unauthenticated; system_context bypasses
    # the restrictive RLS policy installed in migration 0024 (there is no
    # tenant binding on this request — the token IS the tenant scope).
    with system_context():
        wh = db_automation.get_webhook_by_token(token)
        if not wh or not wh.get("enabled"):
            raise HTTPException(
                status_code=404, detail="Invalid or disabled webhook"
            )

        auto = db_automation.get_automation(wh["automation_id"])
        if not auto or not auto.get("latest_version_id"):
            # Automation deleted out from under us, or has no published
            # version yet — surface a clear 404 to the integration.
            raise HTTPException(
                status_code=404,
                detail="Automation has no published version",
            )

        version = db_automation.get_version(auto["latest_version_id"])
        if not version:
            raise HTTPException(
                status_code=404,
                detail="Automation has no published version",
            )

        run = db_automation.create_run(
            automation_version_id=auto["latest_version_id"],
            profile_id=wh.get("profile_id"),
            triggered_by="webhook",
        )
        db_automation.mark_webhook_triggered(wh["id"])

    # Lazy-import the executor — it lives in routers.automations and
    # carries Playwright as a (lazy) transitive import. Importing it at
    # module load time would force the dependency into this router's
    # import graph for no benefit when the webhook receiver is idle.
    from .automations import _execute_run_async

    asyncio.create_task(
        _execute_run_async(run["id"], version, wh.get("profile_id"))
    )

    logger.info(
        "webhook fire: automation=%s run=%s profile=%s",
        wh["automation_id"],
        run["id"],
        wh.get("profile_id"),
    )

    return {
        "received": True,
        "run_id": run["id"],
        "status": run.get("status", "queued"),
    }
